Web/ImageProcessing.Web/Controllers/ImageProcessingController.cs
using ImageProcessing.Data;
using ImageProcessing.Services;
using ImageProcessing.Web.Helpers;
using ImageProcessing.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace ImageProcessing.Web.Controllers
{
    public class ImageProcessingController : Controller
    {
        private readonly IUserService _userService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IImageProcessingService _imageProcessingService;

        public ImageProcessingController(IUserService userService, IHttpContextAccessor httpContextAccessor, IImageProcessingService imageProcessingService)
        {
            _userService = userService;
            _httpContextAccessor = httpContextAccessor;
            _imageProcessingService = imageProcessingService;
        }
        public IActionResult Index()
        {
            var model = new ImageProcessingModel();
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Index(ImageProcessingModel model)
        {
            try
            {
                //Checking for field validation in Model ......
                if (!ModelState.IsValid)
                    return View(model);

                if (model.RequestedImage != null && model.RequestedImage.Length > 0)
                {
                    var fileName = DateTime.Now.Ticks + "_" + Path.GetFileName(model.RequestedImage.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images/requested", fileName);

                    bool exists = System.IO.Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "requested"));
                    if (!exists)
                        System.IO.Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "requested"));
                    exists = System.IO.Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "processed"));
                    if (!exists)
                        System.IO.Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "processed"));

                    using var fileStream = new FileStream(filePath, FileMode.Create);
                    await model.RequestedImage.CopyToAsync(fileStream);
                    model.RequestedImageUrl = Path.Combine("images", "requested", fileName);
                    model.ProcessedImageUrl = Path.Combine("images", "processed", fileName);
                }
                TempData["ResizeSDone"] = await _imageProcessingService.ResizeImage(new Data.Entities.ImageProcessingHistory()
                {
                    Height = model.Height,
                    Width = model.Width,
                    IPQuality = model.IPQuality,
                    RequestedImageUrl = model.RequestedImageUrl,
                    ProcessedImageUrl = model.ProcessedImageUrl,
                    UserId = Convert.ToInt32(_httpContextAccessor.HttpContext.Session.GetInt32("Id")),
                    CreatedOn = DateTime.Now
                });
            }
            catch (Exception ex)
            {
                LogHelper.logger.Error($"{nameof(UserController)},{" - "},{nameof(Index)},{" - "},{ex.Message},{ex.InnerException},{ex.StackTrace}");
            }

            return View(model);
        }
    }
}

Web/ImageProcessing.Web/Controllers/UserController.cs
using ImageProcessing.Data;
using ImageProcessing.Services;
using ImageProcessing.Web.Helpers;
using ImageProcessing.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Win32;

namespace ImageProcessing.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public UserController(IUserService userService, IHttpContextAccessor httpContextAccessor)
        {
            _userService = userService;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            try
            {
                var users = _userService.GetUserAsync();
                return View(users);
            }
            catch (Exception ex)
            {
                LogHelper.logger.Error($"{nameof(UserController)},{" - "},{nameof(Index)},{" - "},{ex.Message},{ex.InnerException},{ex.StackTrace}");
            }
            return View();
        }
        public async Task<IActionResult> Profile()
        {
            try
            {
                var user = await _userService.GetUserByIdAsync(Convert.ToInt32(_httpContextAccessor.HttpContext.Session.GetInt32("Id")));
                return View(new UserModel()
                {
                    Id = user.Id,
                    Firstname = user.Firstname,
                    Lastname = user.Lastname,
                    Email = user.Email,
                    Gender = user.Gender,
                    DOB = user.DOB,
                    Image = user.Image,
                    IsActive = user.IsActive,
                    IsAdmin = user.IsAdmin,
                    Password = SecurityHelper.Decrypt(user.Password),
                });
            }
            catch (Exception ex)
            {
                LogHelper.logger.Error($"{nameof(UserController)},{" - "},{nameof(Profile)},{" - "},{ex.Message},{ex.InnerException},{ex.StackTrace}");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Profile(UserModel user)
        {
            try
            {
                var model = await _userService.GetUserAsync();
                var IsAlreadyRegistered = model.Where(x => x.Email == user.Email).Any();

                //Already register user checking ......
                if (IsAlreadyRegistered && _httpContextAccessor.HttpContext.Session.GetInt32("Id") == null)
                    ModelState.AddModelError(nameof(user.Email), "Email is already registered in system.");

                //Password matching .......
                if (user.Password != user.ConfirmPassword)
                    ModelState.AddModelError(nameof(user.ConfirmPassword), "Password and confirm password does not match.");

                //Checking for field validation in Model ......
                if (!ModelState.IsValid)
                    return View(user);

                if (user.ProfilePicture != null && user.ProfilePicture.Length > 0)
                {
                    var fileName = Path.GetFileName(user.ProfilePicture.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileName);
                    using var fileStream = new FileStream(filePath, FileMode.Create);
                    await user.ProfilePicture.CopyToAsync(fileStream);
                    user.ProfilePictureUrl = "/images/" + fileName;
                }

                //Calling Insert service to register user in database........
                int result = await _userService.InsertUserAsync(new Data.User()
                {
                    Id = user.Id,
                    Firstname = user.Firstname,
                    Lastname = user.Lastname,
                    Email = user.Email,
                    DOB = user.DOB,
                    Gender = user.Gender,
                    Password = SecurityHelper.Encrypt(user.Password),
                    CreatedOn = DateTime.Now,
                    IsActive = true,
                    //IsAdmin = f,
                    Image = user.ProfilePictureUrl

                });

                if (result > 0)
                    return Json(new { result = true, msg = "Profile Updated Successfully." });
            }
            catch (Exception ex)
            {
                LogHelper.logger.Error($"{nameof(UserController)},{" - "},{nameof(Profile)},{" - "},{ex.Message},{ex.InnerException},{ex.StackTrace}");
            }
            return Json(new { result = false, msg = "Something went wrong." });
        }
    }
}

Web/ImageProcessing.Web/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor _context;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>IP</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS Files -->
    <link href="~/assets/css/variables.css" rel="stylesheet">
    <link href="~/assets/css/main.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/toastr.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/toastr.js"></script>
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a href="index.html" class="logo d-flex align-items-center">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="~/assets/img/logo.png" alt=""> -->
                <h1>Image Processing</h1>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    @if (_context.HttpContext.Session.GetString("IsAdmin") == "True")
                    {
                        <li>
                            <a asp-area="Admin" asp-controller="Home" asp-action="Index">
                                Admin
                            </a>
                        </li>
                    }
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="AboutUs">About</a></li>
                    <li><a asp-controller="ImageProcessing" asp-action="Index">Image Things</a></li>

                </ul>
            </nav><!-- .navbar -->

            <div class="position-relative">

                @if (_context.HttpContext.Session.GetInt32("Id") > 0)
                {
                    <nav id="navbar" class="navbar">
                        <ul>
                            <li class="dropdown">
                                <a href="javascript:void()"><span>Welcome - @_context.HttpContext.Session.GetString("Firstname") @_context.HttpContext.Session.GetString("Lastname")! </span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                                <ul>
                                    <li><a asp-controller="User" asp-action="Profile">Profile</a></li>
                                    <li><a asp-controller="Account" asp-action="Signout">Sign out</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                }
                else
                {
                    <nav id="navbar" class="navbar">
                        <ul>
                            <li><a asp-controller="Account" asp-action="Signin">Signin</a></li>
                            <li><a asp-controller="Account" asp-action="Register">Register</a></li>
                        </ul>
                    </nav>
                }


                @* <a href="#" class="mx-2 js-search-open"><span class="bi-search" style="display:none"></span></a>
                <i class="bi bi-list mobile-nav-toggle" style="display:none"></i>

                <!-- ======= Search Form ======= -->
                <div class="search-form-wrap js-search-form-wrap" style="display:none">
                <form action="search-result.html" class="search-form">
                <span class="icon bi-search"></span>
                <input type="text" placeholder="Search" class="form-control">
                <button class="btn js-search-close"><span class="bi-x"></span></button>
                </form>
                </div><!-- End Search Form -->*@


            </div>

        </div>

    </header><!-- End Header -->
    <!-- ======= Main ======= -->
    <main id="main">

        <section id="posts" class="posts">

            @RenderBody()


        </section>
    </main>
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="footer-content">
            <div class="container">

                <div class="row g-5">
                    <div class="col-lg-6" style="margin-right:350px;">
                        <h3 class="footer-heading">About Image Processing</h3>
                        <p>Image Processing provides image processing, compression, resizing, and optimization services to its users. Our website is designed to help website owners and developers improve the performance of their websites by reducing image loading times and improving the user experience.</p>
                        <p>
                            <a asp-controller="Home" asp-action="AboutUs" class="footer-link-more">Learn More</a>
                        </p>
                    </div>
                    <div class="col-6 col-lg-2">
                        <h3 class="footer-heading">Navigation</h3>
                        <ul class="footer-links list-unstyled">
                            <li><a asp-controller="Home" asp-action="Index"><i class="bi bi-chevron-right"></i>Home</a></li>
                            <li><a asp-controller="Home" asp-action="AboutUs"><i class="bi bi-chevron-right"></i>About</a></li>
                            @*<li><a href="contact.html"><i class="bi bi-chevron-right"></i> Contact</a></li>*@
                        </ul>
                    </div>


                </div>
            </div>
        </div>

        <div class="footer-legal">
            <div class="container">

                <div class="row justify-content-between">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        <div class="copyright">
                            © Copyright <strong><span>Image Processing</span></strong>. All Rights Reserved
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
                            <a href="https://www.facebook.com/Dungaranisatish7511" target="_blank" class="facebook"><i class="bi bi-facebook"></i></a>
                            <a href="https://www.instagram.com/satish_dungarani" target="_blank" class="instagram"><i class="bi bi-instagram"></i></a>
                            <a href="https://join.skype.com/invite/UHq3S4c6K1BD" target="_blank" class="google-plus"><i class="bi bi-skype"></i></a>
                            <a href="https://www.linkedin.com/in/satishdungarani" target="_blank" class="linkedin"><i class="bi bi-linkedin"></i></a>
                        </div>

                    </div>

                </div>

            </div>
        </div>

    </footer>
    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


 
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/js/main.js"></script>
    <!-- Vendor JS Files -->
    
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>